launch:
  - arg:
      name: trajectory_follower_mode
      default: trajectory_follower_node
      # option: trajectory_follower_node
      #         smart_mpc_trajectory_follower
      #         dwa_trajectory_follower
      #         none

  - arg:
      name: lateral_controller_mode
      default: pure_pursuit

  - arg:
      name: longitudinal_controller_mode
      default: pid
